# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"youtube" = ""
"instagram" = ""
"meet" = ""
"translate" = ""
"discord" = "ﭮ"
"stack" = ""
"keybr" = ""
"monkeytype" = ""
"linkedin" = ""
"google maps" = "﫴"
"medium" = ""
"steam" = ""
"news" = ""
"opera" = ""
"pinterest" = ""
"quora" = ""
"reddit" = ""
"telegram" = ""
"twitch" = ""
"twitter" = ""
"wikipedia" = ""
"google play" = ""
"imdb" = ""
"amazon" = ""
"xda" = "請"
"pomo" = ""
"android studio" = ""
"keepassxc" = ""
"vlc" = "嗢"
".cpp" = ""
".html" = ""
".java" = ""
".go" = ""
".py" = ""
".js" = ""
".ts" = "ﯤ"
".css" = ""
".rs" = ""
"julia" = ""
"heroku" = ""
"gist" = ""
".hs" = ""
".lhs" = ""
"sql" = ""
# class_g("kitty") = ""
"spotify" = ""
"github" = ""
"zoom" = ""
"rust" = ""
"bluetooth" = ""
"speedtest" = ""
"whatsapp" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"vim" = ""
"studio" = "﬏"
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
[other]
"fallback_icon" = ""
