 require("plugins.packer-config")
 require("plugins.UI.bufferline")
 require("plugins.UI.nvim-ts-autotag")
 require("plugins.UI.colorscheme.catppuccin")
 require("plugins.UI.dashboard")
 require("plugins.UI.indent-blankline")
 require("plugins.UI.notify")
 --require("plugins.UI.lualine")
 require("plugins.UI.feline")

 require("plugins.productivity.discord-presence")
 require("plugins.productivity.nvim-tree")
 require("plugins.productivity.tree-sitter")
 require("plugins.productivity.auto-pairs")
 require("plugins.productivity.telescope")
 require("plugins.productivity.toggleterm")
 require("plugins.productivity.truezen")
 require("plugins.productivity.nvim-plenary")
